### ISSUE TITLE
casStatsFetch() and startup order

### ISSUE THREAD

**Issue by mdavidsaver** [epics-modules/iocStats#23]
Originally reported as https://bugs.launchpad.net/epics-base/+bug/1694966

It isn't safe to call casStatsFetch() until RSRV has initialized successfully.  If iocInit fails between the point where the timer which calls casStatsFetch() is started (device support init() ), and rsrv_init(), then the IOC process will crash when casStatsFetch() is called from the timer thread.

https://github.com/epics-modules/iocStats/blob/0cec4fc67a4d4419c21161d889862766a7690daa/devIocStats/devIocStatsAnalog.c#L405

At a minimum, iocStats should not start this timer until after RSRV has started, if not later. I'd suggest an initHook with initHookAfterCaServerRunning or initHookAfterIocRunning.

**Comment by anjohnson** [comment]
It should be safe to call casStatsFetch() once rsrv_init() has returned, which is initHookAfterCaServerInit. To avoid having to register an initHook though you can just test interruptAccept (declared in dbAccessDefs.h or dbAccess.h) and skip the call to casStatsFetch() when interruptAccept is false (zero).

**Comment by ralphlange** [comment]
Had already been fixed in master at the time of reporting by #21.
