### ISSUE TITLE
Documentation points to the wrong maintainer

### ISSUE THREAD

**Issue by keenanlang** [epics-modules/iocStats#29]
The SLAC documentation page that the README points to states that Stephanie Allison is the developer and maintainer of the module, however she is retired and no longer maintaining it.

Is there a current lead maintainer that the documentation can be pointed to?

**Comment by ralphlange** [comment]
Good question. Are you volunteering?
Point is that this module has quite a number of SLAC specifics, and I would really like to see someone from SLAC being involved, else any change will just too easily break things.
@till-s: who should we ask?

**Comment by till-s** [comment]
Maybe ask Ernest to advise...

**Comment by ralphlange** [comment]
Ok, will do.

**Comment by ralphlange** [comment]
Ernest nominated Kukhee Kim as the new maintainer.
@till-s: can you trigger an update of the SLAC documentation page at http://www.slac.stanford.edu/grp/ssrl/spear/epics/site/devIocStats/ ?

**Comment by simon-ess** [comment]
@keenanlang - I have accepted the role as the maintainer of this repository. The SLAC documentation can be updated accordingly.
