### ISSUE TITLE
PV names in template files

### ISSUE THREAD

**Issue by jeonghanlee** [epics-modules/iocStats#31]
Is it possible to remove **:** in template files ? For example

- from
```
record(mbbo, "$(IOCNAME):ACCESS")
```
- to
```
record(mbbo, "$(IOCNAME)ACCESS")
```

Without it, users have more freedom to select PV name according to site-specific naming convention.

**Comment by anjohnson** [comment]
As suggested this change is not backwards compatible and would break the databases for all existing users, although something like
```
record(mbbo, "$(IOCNAME)$(SEP=:)ACCESS")
```
or similar should be okay. Sites that don't want the colon would have to define SEP to be blank or some other character, existing sites should not be affected at all by the change.

What do ESS PV names look like if you aren't using colons for separators?

**Comment by jeonghanlee** [comment]
ESS has the following naming convention
```
Sec-Sub : Dis-Dev-Idx :ACCESS
```
My problem is to use ONE IocState for many Dev, for example. my ioc has three devices 
```
*-PS-01
*-PS-02
*-PS-03
```
within the one IOC, so I have no way to inject an iocStats without creating the virtual iocStats device. :)  
If there is no : before ACCESS, I may create :IocState-ACCESS (oh ESS! :) ) as PVs.

**Comment by anjohnson** [comment]
The iocStats databases originally came from SLAC and I don't know for sure how they are used there, but in addition to the `$(IOCNAME):ACCESS` record in ioc.template there is also a separate access.db file which provides two mbbo records `$(DEV)ACCESS` and `$(DEV)FBCK` that you could load or instantiate as many times as you have devices; they don't have a `:` in the names.

**Comment by MarkRivers** [comment]
It would be nice to eliminate the colon but as Andrew said it would really need to be done in a way that preserves backwards compatibility.  In areaDetector IOCs for example, we define a single PREFIX environment variable, e.g. 13SIM1:, which contains the colon.  This prefix is used when loading all databases, including (optionally) iocStats.  This means that the iocStats PVs all have 2 colons in them:
```
epics> dbgrep *"::"*
13IDC-PIL::HEARTBEAT
13IDC-PIL::START_CNT
13IDC-PIL::GTIM_RESET
13IDC-PIL::ACCESS
13IDC-PIL::CA_UPD_TIME
13IDC-PIL::FD_UPD_TIME
13IDC-PIL::LOAD_UPD_TIME
13IDC-PIL::MEM_UPD_TIME
13IDC-PIL::ST_SCRIPT
13IDC-PIL::EPICS_VERSION
13IDC-PIL::APP_DIR
13IDC-PIL::GTIM_ERR_CNT
13IDC-PIL::FD_FREE
13IDC-PIL::READACF
13IDC-PIL::SYSRESET
13IDC-PIL::SysReset
13IDC-PIL::CA_CLNT_CNT
13IDC-PIL::CA_CONN_CNT
13IDC-PIL::RECORD_CNT
13IDC-PIL::FD_MAX
13IDC-PIL::FD_CNT
13IDC-PIL::SYS_CPU_LOAD
13IDC-PIL::IOC_CPU_LOAD
13IDC-PIL::LOAD
13IDC-PIL::CPU_CNT
13IDC-PIL::SUSP_TASK_CNT
13IDC-PIL::MEM_USED
13IDC-PIL::MEM_FREE
13IDC-PIL::MEM_MAX
13IDC-PIL::PROCESS_ID
13IDC-PIL::PARENT_ID
13IDC-PIL::GTIM_TIME
13IDC-PIL::STARTTOD
13IDC-PIL::TOD
13IDC-PIL::ST_SCRIPT1
13IDC-PIL::ST_SCRIPT2
13IDC-PIL::KERNEL_VERS
13IDC-PIL::EPICS_VERS
13IDC-PIL::HOSTNAME
13IDC-PIL::APP_DIR1
13IDC-PIL::APP_DIR2
13IDC-PIL::UPTIME
13IDC-PIL::ENGINEER
13IDC-PIL::LOCATION
13IDC-PIL::GTIM_CUR_SRC
13IDC-PIL::GTIM_EVT_SRC
13IDC-PIL::GTIM_HI_SRC
13IDC-PIL::CA_ADDR_LIST
13IDC-PIL::CA_CONN_TIME
13IDC-PIL::CA_AUTO_ADDR
13IDC-PIL::CA_RPTR_PORT
13IDC-PIL::CA_SRVR_PORT
13IDC-PIL::CA_MAX_ARRAY
13IDC-PIL::CA_SRCH_TIME
13IDC-PIL::CA_BEAC_TIME
13IDC-PIL::TIMEZONE
13IDC-PIL::TS_NTP_INET
13IDC-PIL::IOC_LOG_PORT
13IDC-PIL::IOC_LOG_INET
```
The OPI screens have this additional colon in them as well, e.g. ioc_stats_soft.adl:
```
"text update" {
        object {
                x=125
                y=68
                width=190
                height=15
        }
        monitor {
                chan="$(ioc):TOD"
                clr=14
                bclr=4
        }
        format="string"
        limits {
        }
}
```
If the colon were removed from the the .template files it would also need to be removed from the opi files.

Mark

**Comment by MarkRivers** [comment]
Using SEP=: works for template files.  But does it work for OPI files?  The OPI files all contain $(ioc):, i.e. the : is hardcoded.  If one loads a template file with "SEP=" to eliminate the colon there one will need to have a colon in the $(ioc) patten or the OPI files will not work. One will also need to pass a different value for $(IOC) to the template file and $(ioc) to the OPI file.

**Comment by jeonghanlee** [comment]
@MarkRivers   No it doesn't work for existent OPI files. OPI is strongly dependent upon final PV names inflated  from substitutions files based on templates files.  Thus, we need another set of opi screens.  I am thinking to  build the "bob" screen for latest CS-studio to have only one prefix, i.e., $(P)TOD.

**Comment by anjohnson** [comment]
Hi @jeonghanlee — I'm still trying to understand your use-case before I can answer your PR #32 . Earlier in this thread you wrote:
> ESS has the following naming convention
> ```
> Sec-Sub : Dis-Dev-Idx :ACCESS
> ```
> My problem is to use ONE IocState for many Dev, for example. my ioc has three devices
> ```
> *-PS-01
> *-PS-02
> *-PS-03
> ```
> within the one IOC

You can have multiple devices running on one IOC, but most of the iocStats databases were designed to only be loaded once per IOC, because they provide information that about the state of the IOC itself, not the devices running on it. The `$(IOCNAME):ACCESS` PV may be a poor example because it isn't obviously per-IOC information, but something like `$(IOCNAME):TOD` which follows in the same template file should really only need to be loaded once.

In your example IOC with 3 devices, were you planning to load the ioc.db file 3 times, once for each device so you would for example get PVs named `x-PS-01:TOD`, `x-PS-02:TOD` and `x-PS-03:TOD`? I don't understand why you might want that but would creating 3 extra aliases for a single record that provides that information be an acceptable solution? You can load those aliases from a separate .db file (after loading the other iocStats databases), although you would have to create that file yourself. Here's what part of it might look like:

```
alias("$(IOCNAME):ACCESS", "$(PREFIX)ACCESS")
alias("$(IOCNAME):STARTTOD", "$(PREFIX)STARTTOD")
alias("$(IOCNAME):TOD", "$(PREFIX)TOD")
# etc.
```

You could of course also add your own PVs so that say the `$(PREFIX)ACCESS` PV was a separate record.

**Comment by jeonghanlee** [comment]
@anjohnson  I had a plan to explain what I want in possible spare time in epics meeting, but I failed.  I selected the wrong PV name in order to explain it. You were confused by that PV name (ACCESS). 

The following snippet of my startup script :

```sh

epicsEnvSet(P, TS2-010RFC:)
epicsEnvSet(R, RFS-SOLPS)
epicsEnvSet(R1, $(R)-001:)
epicsEnvSet(R2, $(R)-002:)
epicsEnvSet(R3, $(R)-003:)
epicsEnvSet(IOC, $(P)$(R))


iocshLoad "iocStats.iocsh" "IOC=$(IOC)-IocStats"
iocshLoad "gen5kWPS_n.iocsh" "MOXA_PORT=4001,PREFIX=$(P)$(R1)"
iocshLoad "gen5kWPS_n.iocsh" "MOXA_PORT=4002,PREFIX=$(P)$(R2)"
iocshLoad "gen5kWPS_n.iocsh" "MOXA_PORT=4003,PREFIX=$(P)$(R3)"

```

As you see there, we have three devices in one IOC. The final PV name

```
TS2-010RFC:RFS-SILPS-001:RMT_SP
TS2-010RFC:RFS-SILPS-002:RMT_SP
TS2-010RFC:RFS-SILPS-002:RMT_SP
```

But, iocStats has 
```
TS2-010RFC:RFS-SILPS-IocStats::HEARTBEAT
```
because of the hard-coded : in all template files. That is the exact same as in https://github.com/epics-modules/iocStats/issues/31#issuecomment-415981581

From modified template files ```(SEP=:)```, I can build the substitution file such as
```
file iocEnvVar.template
{
pattern { IOCNAME  ,  SEP        , ENVNAME      , ENVVAR                          , ENVTYPE }
	{ "$(IOC)" , "$(SEPTYPE)", CA_ADDR_LIST , EPICS_CA_ADDR_LIST              , epics   } 
	{ "$(IOC)" , "$(SEPTYPE)", CA_CONN_TIME , EPICS_CA_CONN_TMO               , epics   } 
	{ "$(IOC)" , "$(SEPTYPE)", CA_AUTO_ADDR , EPICS_CA_AUTO_ADDR_LIST         , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", CA_RPTR_PORT , EPICS_CA_REPEATER_PORT          , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", CA_SRVR_PORT , EPICS_CA_SERVER_PORT            , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", CA_MAX_ARRAY , EPICS_CA_MAX_ARRAY_BYTES        , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", CA_SRCH_TIME , EPICS_CA_MAX_SEARCH_PERIOD      , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", CA_BEAC_TIME , EPICS_CA_BEACON_PERIOD          , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", TIMEZONE     , EPICS_TIMEZONE                  , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", TS_NTP_INET  , EPICS_TS_NTP_INET               , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", IOC_LOG_PORT , EPICS_IOC_LOG_PORT              , epics   }
	{ "$(IOC)" , "$(SEPTYPE)", IOC_LOG_INET , EPICS_IOC_LOG_INET              , epics   }
}

```
Then, the snippet of iocStats is
```
#- $(IOC)$(SEP=:)ACCESS
dbLoadRecords("iocAdminSoft-ess.db", "IOC=$(IOCNAME), SEPTYPE=$(SEP=IocStats:)")
```

After this,
```
iocshLoad "iocStats.iocsh" "IOC=$(IOC)"
```

will return
```
TS2-010RFC:RFS-SILPS-IocStats:HEARTBEAT
```

Since ESS naming convention allows me to use : in two times only, I would like to ask this issue. Please let me know, if you and other maintainer are not happy about these changes. I can keep using the local "forked" repository instead of the main stream.

**Comment by MarkRivers** [comment]
```
dbLoadRecords("iocAdminSoft-ess.db", "IOC=$(IOCNAME), SEPTYPE=$(SEP=IocStats:)")
```
I think this would be clearer if you did it this way:

```
dbLoadRecords("iocAdminSoft-ess.db", "IOC=$(IOCNAME)IocStats, SEPTYPE=$(SEP=:)")
```
Then it would be clear that SEP is meant to just be the separator.  It could also be done as
```
dbLoadRecords("iocAdminSoft-ess.db", "IOC=$(IOCNAME)IocStats:, SEPTYPE=$(SEP=)")
```
where the : is part of IOC, which is how we use it.

**Comment by jeonghanlee** [comment]
@MarkRivers  yes, your method is much more clear than I did. Thanks.   
@anjohnson  please give me more time to think what is better for the community, because I've found my argument is not right generically during these discussions.

**Comment by anjohnson** [comment]
Mark's examples shows that you may not need to add the `SEP` macros at all if you do something like this:
```
dbLoadRecords("iocAdminSoft-ess.db", "IOC=$(IOCNAME)IocStats")
```

**Comment by MarkRivers** [comment]
I do think making the : optional in iocStats databases by using SEP is useful.  In areaDetector we load all databases using using $PREFIX, where for example PREFIX=13SIM:.  The problem is that iocStats then ends up with double colons in each PV name.

Is the macro processing in OPI display files done using the same library, so that we could use $(SEP=:) in display files as well?

**Comment by jeonghanlee** [comment]
@anjohnson and @MarkRivers  Thank you for the discussion. My argument was based on the assumption, which we have **one PRIFIX** at the beginning of a startup script, which is the same as https://github.com/epics-modules/iocStats/issues/31#issuecomment-420327882 . 

I was in that logic trap. So now it doesn't matter it has SEP or not.  Now I am thinking that assumption is whether "must-follow" one is or not.  I am not sure right now. 

However, I think, the pull request #32 may be still useful for any future release, because of what @MarkRivers mentioned in https://github.com/epics-modules/iocStats/issues/31#issuecomment-420327882

**Comment by prjemian** [comment]
I am definitely in favor of making this separator configurable.  How to handle use in the screen files must be addressed.

**Comment by jeonghanlee** [comment]
no issue anymore, so I close it.
