### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by jeonghanlee** [epics-modules/iocStats#33]
Is there any plan for release version of this module?

**Comment by ralphlange** [comment]
I was suggesting to release a new version soon to @kukhee on Aug 10 - he agreed and put it on his to-do list.

Currently there's an expected update on #30 (as @mark0n updated the underlying changes in base); as soon as this is in, we should be ready.

**Comment by jeonghanlee** [comment]
@ralphlange  thank you.

**Comment by MarkRivers** [comment]
I have just added a new pull request.  It adds the ability to created op/edl/autoconvert/*, op/ui/autoconvert/*, and op/opi/autoconvert/* files from the medm .adl files.  There are thus now functioning OPI screens for most of the major display managers.

I also simplified configure/RELEASE.  This may have a conflict with master that needs to be resolved.

I am hoping this can be merged before the next release is tagged.

**Comment by ralphlange** [comment]
Wohooo! :1st_place_medal:

**Comment by mark0n** [comment]
@ralphlange I just pushed new versions of my code that add the high-water mark feature you suggested. Please review/test.

**Comment by keenanlang** [comment]
Looking to put together a release of synApps 6_1 by the end of next month, any updates on getting a tagged release ready?
